os: linux
dist: focal
arch: arm64-graviton2
group: dev

jobs:
  include:
        - language: cpp
          compiler: clang
          script:
            - g++ hello.cpp  
        - language: python
          script:
            - python hello.py
        - language: ruby
          rvm:
            - 2.5
          script:
            - ruby hello.rb
